add missing random-access-memory@3 (#1)
fixes:

```
Error: Cannot find module 'random-access-memory'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/robert/bitfinex/hypermarket/node_modules/hypercore-multi-key/storage.js:2:13)
```